name: Auto Deploy PPV Soluciones to Hetzner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Production Hetzner
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SSH Auto-Pull on Hetzner Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 167.233.122.18
          username: root
          password: ${{ secrets.HETZNER_PASSWORD }}
          script: |
            cd /var/www/ppvsoluciones
            git pull origin main
